const  types = { 
    GET_CURR_WEATHER_BY_SEARCH : "Get_CURR_WEATHER_BY_SEARCH", 
    GET_FAVORITES : "Get_FAVORITES",
    GET_USER_LOC:'GET_USER_LOC',
    CHANGE_TEMPERATURE:'CHANGE_TEMPERATURE'
};
export default types;